name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
  
      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test
      
       
